name: Native Compile for Releases

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: Grant execute permission for Gradle (Linux & macOS)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Run Native Compile
        run: ./gradlew nativeCompile "-Pversion=${{ github.event.release.tag_name }}"
        env:
          USERNAME: ${{ secrets.GITHUB_ACTOR }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true

      - name: Upload Release Assets (for Windows)
        uses: softprops/action-gh-release@v2
        if: runner.os == 'Windows'
        with:
          files: lwjgl3/build/native/QuantumVoxel-windows.exe
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets (for Linux)
        uses: softprops/action-gh-release@v2
        if: runner.os == 'Linux'
        with:
          files: lwjgl3/build/native/QuantumVoxel-linux
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets (for macOS)
        uses: softprops/action-gh-release@v2
        if: runner.os == 'macOS'
        with:
          files: lwjgl3/build/native/QuantumVoxel-macos
          token: ${{ secrets.GITHUB_TOKEN }}
