name: Native Compile for Artifacts

on:
  push:
    branches:
      - main
      - 'channels/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '23'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run Native Compile
        run: ./gradlew nativeCompile -Psnapshot=true
        env:
          USERNAME: ${{ secrets.GITHUB_ACTOR }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: native-binaries
          path: lwjgl3/build/native/nativeCompile/**
          retention-days: 2
