name: Native Compile for Artifacts

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run Native Compile
        run: ./gradlew publish nativeCompile -Pversion=${{ github.event.release.tag_name }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: lwjgl3/build/native/**
          token: ${{ secrets.GITHUB_TOKEN }}
